import Head from "next/head";
import { useState } from "react";

function Modal(props: {showModal: boolean, setShowModal: (showModal: boolean) => void}) {
    if (!props.showModal) return null;
    return (
        <>
            <div
                className="justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none"
            >
                <div className="relative w-auto my-6 mx-auto max-w-3xl">
                    {/*content*/}
                    <div className="border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none">
                        {/*header*/}
                        <div className="flex items-start justify-between p-5 border-b border-solid border-slate-200 rounded-t">
                            <h3 className="text-3xl font-semibold">
                                Modal Title
                            </h3>
                            <button
                                className="p-1 ml-auto bg-transparent border-0 text-black opacity-5 float-right text-3xl leading-none font-semibold outline-none focus:outline-none"
                                onClick={() => props.setShowModal(false)}
                            >
                                <span className="bg-transparent text-black opacity-5 h-6 w-6 text-2xl block outline-none focus:outline-none">
                                    ×
                                </span>
                            </button>
                        </div>
                        {/*body*/}
                        <div className="relative p-6 flex-auto">
                            <p className="my-4 text-slate-500 text-lg leading-relaxed">
                                I always felt like I could do anything. That’s the main
                                thing people are controlled by! Thoughts- their perception
                                of themselves! They're slowed down by their perception of
                                themselves. If you're taught you can’t do anything, you
                                won’t do anything. I was taught I could do everything.
                            </p>
                        </div>
                        {/*footer*/}
                        <div className="flex items-center justify-end p-6 border-t border-solid border-slate-200 rounded-b">
                            <button
                                className="text-red-500 background-transparent font-bold uppercase px-6 py-2 text-sm outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                                type="button"
                                onClick={() => props.setShowModal(false)}
                            >
                                Close
                            </button>
                            <button
                                className="bg-emerald-500 text-white active:bg-emerald-600 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                                type="button"
                                onClick={() => props.setShowModal(false)}
                            >
                                Save Changes
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div className="opacity-25 fixed inset-0 z-40 bg-black"></div>
        </>
    );
}


export default function Home() {
    const [showModal, setShowModal] = useState(false);
    const ListItem = (props: {content: string}) => {
        return (
            <div className="flex items-center h-1/6 w-1/3" onClick={() => setShowModal(true)}>
                <li className="border border-grey-800 rounded py-2 px-2 w-full hover:bg-slate-200 cursor-pointer transition">
                    {props.content}
                </li>
            </div>
        )
    }

    return (
        <>
            <Head>
                <title>🍽 Resto menu 🍽</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-teal-50 min-h-screen font-nunito">
                <h1 className="font-normal text-3xl text-center">¡Bienvenido!</h1>
                <div className="mx-8 my-4">
                    <p>
                        Tus próximos pasos son &rarr;
                    </p>
                    <div className="mx-4 my-10 h-96">
                        <ol className="list-decimal p-0 list-inside h-full">
                            <ListItem content="Crear un plato de tu menú"/>
                            <ListItem content="Elegir un formato para tu menú"/>
                            <ListItem content="Elegir un nombre para tu menú online"/>
                        </ol>
                    </div>
                </div>
            <Modal showModal={showModal} setShowModal={setShowModal}/>
            </main>
        </>
    );
}
