import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import CreateDishModal from "~/components/modals/CreateDishModal";

export default function Home() {
    const [showModal, setShowModal] = useState(false);
    const ListItem = useCallback((props: {content: string}) => <div className="flex items-center h-1/6 w-1/3" onClick={() => setShowModal(true)}>
        <li className="border border-grey-800 rounded py-2 px-2 w-full hover:bg-slate-200 cursor-pointer transition">
            {props.content}
        </li>
    </div>, [setShowModal])

    useEffect(() => {
        console.log("home")
    })

    return (
        <>
            <Head>
                <title>🍽 Resto menu 🍽</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-teal-50 min-h-screen font-nunito">
                <h1 className="font-normal text-3xl text-center">¡Bienvenido!</h1>
                <div className="mx-8 my-4">
                    <p>
                        Tus próximos pasos son &rarr;
                    </p>
                    <div className="mx-4 my-10 h-96">
                        <ol className="list-decimal p-0 list-inside h-full">
                            <ListItem content="Crear un plato de tu menú"/>
                            <ListItem content="Elegir un formato para tu menú"/>
                            <ListItem content="Elegir un nombre para tu menú online"/>
                        </ol>
                    </div>
                </div>
                <CreateDishModal showModal={showModal} setShowModal={setShowModal}/>
            </main>
        </>
    );
}
